### ISSUE TITLE
Support arrow key navigation on Linux

### ISSUE THREAD

**Issue by pattontim** [jrupac/tasky#36]
Because the output utilizes UTF-8, arrow keys do not function as expected on Linux because it interferes with the readline module. Arrow keys should let you edit typed commands and use the up arrow to cycle through previous commands. You may find a few considerations in the attached link. 

https://github.com/jarun/googler/issues/86

**Comment by jrupac** [comment]
Thanks for the report.

I think just moving to Python 3 will address this and is also overdue anyway. I've just pushed dfc6b20f8d6664af9efe0e23d3be3723241bb363 to a new python3 branch along with a `readline` import which addresses this. Let me know if that works.

**Comment by pattontim** [comment]
Arrow navigation is operational in that branch on linux, submitted a PR with updated readme information pertaining to the changes.
