### ISSUE TITLE
filter by list name

### ISSUE THREAD

**Issue by nickylimjj** [jrupac/tasky#38]
It current returns all the lists. Can i indicate which list i want?

**Comment by jrupac** [comment]
You can specify the tasklist to print by the `--tasklist` flag, whose value is the printed numeral to the left of the name (you can have multiple task lists of the same name so this is a unique way of specifying it). 

E.g.:

```shell
$ ./tasky.py -l
Printing all task lists...
0 Personal (empty)
1 Grocery List
  0 [ ] task4
  1 [ ] Pay my phone bill
    2 [ ] test3
2 Néw list (empty)
3 Goliath
  0 [ ] asdf
4 Goliath
  0 [ ] aa

$ ./tasky.py -l --tasklist 3
Printing Task List 3...
3 Goliath
  0 [ ] asdf

```
